version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
    time: "01:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  cooldown:
    default-days: 5
    include:
      - "*"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  cooldown:
    default-days: 5
    include:
      - "*"
